// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlxD7XfkIdHiFdpq3pV-vQ5CsuJ8cMEo',
    appId: '1:785542072257:web:2cf3a39ebf7c67b39f5140',
    messagingSenderId: '785542072257',
    projectId: 'cicdcicd',
    authDomain: 'cicdcicd.firebaseapp.com',
    storageBucket: 'cicdcicd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTc8vRAQuBqS_K36IBLXq6VOA-hFXO_dk',
    appId: '1:785542072257:android:55359829ed8c34289f5140',
    messagingSenderId: '785542072257',
    projectId: 'cicdcicd',
    storageBucket: 'cicdcicd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4WrUTfkMQHLTzzYGbDrONDvNJwa5lHEA',
    appId: '1:785542072257:ios:83876ff01013d9b09f5140',
    messagingSenderId: '785542072257',
    projectId: 'cicdcicd',
    storageBucket: 'cicdcicd.firebasestorage.app',
    iosBundleId: 'com.example.cicdPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4WrUTfkMQHLTzzYGbDrONDvNJwa5lHEA',
    appId: '1:785542072257:ios:83876ff01013d9b09f5140',
    messagingSenderId: '785542072257',
    projectId: 'cicdcicd',
    storageBucket: 'cicdcicd.firebasestorage.app',
    iosBundleId: 'com.example.cicdPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVlxD7XfkIdHiFdpq3pV-vQ5CsuJ8cMEo',
    appId: '1:785542072257:web:aad53dbe84bbc0be9f5140',
    messagingSenderId: '785542072257',
    projectId: 'cicdcicd',
    authDomain: 'cicdcicd.firebaseapp.com',
    storageBucket: 'cicdcicd.firebasestorage.app',
  );
}
